"""Deterministic synthetic chain identities and generated boundary fixtures.

Why this module exists
----------------------
The committed documents under ``tests/fixtures/evidence/`` must be
*producer-shaped* (so the real verifier code paths are exercised) and at the
same time carry *no identity of any recorded run* (so nothing in the
repository can be presented as, or quietly depend on, a development receipt).
Those two requirements meet in the chain identities: addresses, transaction
hashes, code checksums, block hashes, node IDs, validator keys and
timestamps. This module is the single definition of how a synthetic identity
is derived, so that

* the committed fixtures can be checked -- not merely asserted -- to contain
  only synthetic identities (``identity_findings`` below, used by
  ``tests/unit/runner/test_synthetic_evidence.py``), and
* the two boundary fixtures (Go query-error classification and the Wasm
  ``query_chain`` ABI report) are regenerated byte-for-byte from code
  (``boundary_fixture_files``), which the same test pins against the files on
  disk.

Two kinds of document share that contract and must not be confused:

* The four live-context documents are *identity-scrubbed derivations of
  former development receipts*. ``renumber_identities`` replaced every
  address, transaction and block hash, code checksum, node id, validator
  public key, timestamp, run id, host path and run label with a seed
  derivation; the recorded economic arithmetic (amounts, heights, epochs,
  gas, balances, runtime versions, event attributes) was deliberately kept so
  the verifier's cross-field rules still meet producer-shaped numbers. They
  therefore retain a partial regression on recorded *arithmetic shape* and
  none on recorded *identities*; they are never live receipts.
* The Go and Wasm boundary fixtures are generated by ``boundary_fixture_files``
  from the constants in this module; no value in them was ever recorded.

Every derivation is ``SHA-256(SEED + ":" + label)``; the label names the
document and the role or ordinal of the identity. Nothing here reads a chain,
Docker, Git history or any recorded document.

All fixtures are synthetic. No network, Docker, or live chain calls.
"""

from __future__ import annotations

import base64
import hashlib
import json
import re
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, Iterable, Iterator, List, Optional, Tuple

#: Prefix of every derivation label. Changing it changes every synthetic
#: identity and therefore every committed fixture; the pinning test will say so.
SEED = "forward-e2e synthetic fixture"

#: Schema identifier of the ``synthetic_fixture`` block each committed JSON
#: document carries. Version 2 adds the machine-checkable identity map.
SCHEMA = "forward-e2e.synthetic-fixture/2"

#: Fixed origin of the synthetic clock. Ordinals are minutes past it, so the
#: relative order of timestamps inside one document is preserved while no
#: fixture carries a wall-clock time of any real run.
CLOCK_ORIGIN = datetime(2026, 1, 1, tzinfo=timezone.utc)

#: Revision identifiers that are *pins of the product under test*, not run
#: identities: the harness's protobuf/ABI pin, the Gonka and Marketplace
#: commits every synthetic context is attributed to, and the historical
#: prepared-overlay commit the legacy-shape test needs to differ from the
#: source commit. They are shared with ``real_fixtures.py`` and
#: ``scripts/acceptance_harness.py`` and are allowed to appear verbatim.
REVISION_CONSTANTS = {
    "379bebced638aeb5e6077bfd51c986f898443832": "EXPECTED_PROTO_SHA (scripts/acceptance_harness.py)",
    "29a58fcf64b87967cb874b6169ce2c61e1f269b1": "GONKA_SOURCE_SHA (real_fixtures.py)",
    "f4518654e967b25d1479660115c13f67bace18df": "MARKETPLACE_SHA (real_fixtures.py)",
    "c5afa458de7eb8affa7020f1d0fcd4635ba1fd42": "GONKA_PREPARED_SHA (real_fixtures.py)",
}

BECH32_HRP = "gonka"
_BECH32_CHARSET = "qpzry9x8gf2tvdw0s3jn54khce6mua7l"


# ---------------------------------------------------------------------------
# derivations
# ---------------------------------------------------------------------------
def _digest(label: str) -> bytes:
    return hashlib.sha256(f"{SEED}:{label}".encode("utf-8")).digest()


def synthetic_hex(label: str, *, length: int = 64, upper: bool = False) -> str:
    """Hex digits derived from ``label``; ``length`` <= 64."""
    text = _digest(label).hex()[:length]
    return text.upper() if upper else text


def synthetic_tx_hash(document: str, ordinal: int) -> str:
    """Upper-case 64-hex transaction (or block/app) hash number ``ordinal`` of a document."""
    return synthetic_hex(f"{document}:tx:{ordinal}", upper=True)


def synthetic_sha256(document: str, ordinal: int) -> str:
    """Lower-case 64-hex content digest number ``ordinal`` of a document (code checksums, manifests)."""
    return synthetic_hex(f"{document}:sha256:{ordinal}")


def synthetic_hex40(document: str, ordinal: int, *, upper: bool = False) -> str:
    """40-hex identifier number ``ordinal`` (node IDs, validator addresses, non-pinned Git SHAs)."""
    return synthetic_hex(f"{document}:hex40:{ordinal}", length=40, upper=upper)


def synthetic_pubkey(document: str, label: str) -> str:
    """Base64 of 32 derived bytes, the shape of a Tendermint Ed25519 public key."""
    return base64.b64encode(_digest(f"{document}:pubkey:{label}")).decode("ascii")


def synthetic_timestamp(ordinal: int, *, nanoseconds: bool = False) -> str:
    """``ordinal`` minutes after the synthetic clock origin, RFC 3339 with ``Z``."""
    moment = CLOCK_ORIGIN + timedelta(minutes=ordinal)
    text = moment.strftime("%Y-%m-%dT%H:%M:%S")
    return text + (".000000000Z" if nanoseconds else "Z")


def synthetic_run_id(document: str) -> str:
    return f"synthetic-{document}"


def _bech32_polymod(values: List[int]) -> int:
    generator = (0x3B6A57B2, 0x26508E6D, 0x1EA119FA, 0x3D4233DD, 0x2A1462B3)
    checksum = 1
    for value in values:
        top = checksum >> 25
        checksum = ((checksum & 0x1FFFFFF) << 5) ^ value
        for index in range(5):
            checksum ^= generator[index] if ((top >> index) & 1) else 0
    return checksum


def _bech32_hrp_expand(hrp: str) -> List[int]:
    return [ord(c) >> 5 for c in hrp] + [0] + [ord(c) & 31 for c in hrp]


def _bech32_create_checksum(hrp: str, data: List[int]) -> List[int]:
    values = _bech32_hrp_expand(hrp) + data
    polymod = _bech32_polymod(values + [0, 0, 0, 0, 0, 0]) ^ 1
    return [(polymod >> 5 * (5 - index)) & 31 for index in range(6)]


def _convert_bits(data: bytes, from_bits: int, to_bits: int) -> List[int]:
    accumulator = 0
    bits = 0
    result: List[int] = []
    max_value = (1 << to_bits) - 1
    for value in data:
        accumulator = (accumulator << from_bits) | value
        bits += from_bits
        while bits >= to_bits:
            bits -= to_bits
            result.append((accumulator >> bits) & max_value)
    if bits:
        result.append((accumulator << (to_bits - bits)) & max_value)
    return result


def bech32_encode(hrp: str, payload: bytes) -> str:
    """Standard Bech32 (BIP-173) encoding, as Cosmos SDK addresses use."""
    data = _convert_bits(payload, 8, 5)
    combined = data + _bech32_create_checksum(hrp, data)
    return hrp + "1" + "".join(_BECH32_CHARSET[d] for d in combined)


def synthetic_address(document: str, role: str, *, contract: bool = False) -> str:
    """A valid Bech32 ``gonka1...`` address derived from the document and role.

    Accounts are 20-byte payloads (44 characters), CosmWasm contracts 32-byte
    payloads (64 characters), exactly as the chain renders them, so the
    documents keep the producer's string lengths.
    """
    size = 32 if contract else 20
    return bech32_encode(BECH32_HRP, _digest(f"{document}:address:{role}")[:size])


# ---------------------------------------------------------------------------
# machine check: a document may only contain synthetic identities
# ---------------------------------------------------------------------------
#: Any lowercase Bech32 string with at least an account-sized payload (20
#: bytes = 32 data characters + 6 checksum characters), whatever its
#: human-readable part: ``gonka1``, ``cosmos1``, ``wasm1``, ``gonkavaloper1``.
#: A recorded address of a foreign prefix is as much a dependency on a run as
#: a ``gonka1`` one. ``find_addresses`` verifies the checksum before a
#: candidate counts, which is what keeps a lowercase hex digest -- it shares
#: 14 of the 32 data characters -- from being misread as an address.
ADDRESS_RE = re.compile(r"(?<![a-z0-9])[a-z]{1,83}1[02-9ac-hj-np-z]{38,}(?![02-9ac-hj-np-z])")
HEX64_UPPER_RE = re.compile(r"(?<![0-9A-Fa-f])[0-9A-F]{64}(?![0-9A-Fa-f])")
HEX64_LOWER_RE = re.compile(r"(?<![0-9A-Fa-f])[0-9a-f]{64}(?![0-9A-Fa-f])")
HEX40_RE = re.compile(r"(?<![0-9A-Fa-f])[0-9a-fA-F]{40}(?![0-9A-Fa-f])")
#: RFC 3339 date-times in every spelling the producers use: ``Z`` (the
#: harness's ``utc_now`` and Tendermint's nanosecond block times), a numeric
#: offset (``prepare_runtime_snapshot`` writes ``datetime.isoformat()``, i.e.
#: ``+00:00``) and, so that nothing slips through for lack of a designator,
#: no zone at all.
TIMESTAMP_RE = re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})?")
_TIMESTAMP_PARTS_RE = re.compile(
    r"(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d+))?(?:(Z)|([+-])(\d{2}):(\d{2}))?"
)
#: Base64 of exactly 32 bytes (43 characters plus one pad): the shape of a
#: Tendermint Ed25519 public key as ``status.validator_info.pub_key.value``
#: renders it. A recorded validator key identifies the recorded network.
PUBKEY_RE = re.compile(r"(?<![A-Za-z0-9+/=])[A-Za-z0-9+/]{43}=(?![A-Za-z0-9+/=])")
#: Strings that would betray a recorded run: host and runner paths (developer
#: home directories, macOS and Linux temporary directories, the runner
#: container's ``/workspace`` sources and ``/out`` output mounts), old run
#: folders and dated run labels. Container paths that the producers write by
#: design (``/app/harness/go_boundary`` in the Go report) and the ``/synthetic/``
#: prefix of the scrubbed store paths are not in this list on purpose.
FORBIDDEN_SUBSTRINGS = (
    "/home/",
    "/root/",
    "/Users/",
    "/private/",
    "/tmp/",
    "/var/folders/",
    "/workspace/",
    "/out/",
    "forward-e2e-runtime",
    "docs/reviews",
    "2026-09-",
    "20260910",
    "20260909",
)


def bech32_verify(candidate: str) -> bool:
    """True when ``candidate`` is a checksum-valid Bech32 string (BIP-173)."""
    hrp, separator, data = candidate.rpartition("1")
    if not separator or not hrp or len(data) < 6 or any(ch not in _BECH32_CHARSET for ch in data):
        return False
    values = [_BECH32_CHARSET.index(ch) for ch in data]
    return _bech32_polymod(_bech32_hrp_expand(hrp) + values) == 1


def find_addresses(text: str) -> List[str]:
    """Every checksum-valid Bech32 address in ``text``, of any human-readable part."""
    return [candidate for candidate in ADDRESS_RE.findall(text) if bech32_verify(candidate)]


def on_synthetic_clock(stamp: str) -> bool:
    """True when ``stamp`` is a whole number of minutes after ``CLOCK_ORIGIN``
    within the origin's first day, however its zone is spelled.

    Parsed by hand rather than with ``datetime.fromisoformat`` so that a
    nine-digit Tendermint fraction, a ``Z`` designator and a missing
    designator are all read the same way on every supported Python version.
    The offset is applied before comparing, so ``2025-12-31T19:00:00-05:00``
    is the origin and a wall-clock time cannot hide behind its zone spelling.
    """
    match = _TIMESTAMP_PARTS_RE.fullmatch(stamp)
    if match is None:
        return False
    year, month, day, hour, minute, second, fraction, _zulu, sign, zone_hours, zone_minutes = match.groups()
    # The synthetic clock ticks in whole minutes; any seconds or fraction is a
    # recorded instant, whatever the date says.
    if int(second) != 0 or (fraction is not None and int(fraction) != 0):
        return False
    try:
        moment = datetime(int(year), int(month), int(day), int(hour), int(minute), tzinfo=timezone.utc)
    except ValueError:
        return False
    if sign is not None:
        offset = timedelta(hours=int(zone_hours), minutes=int(zone_minutes))
        moment = moment - offset if sign == "+" else moment + offset
    return CLOCK_ORIGIN <= moment < CLOCK_ORIGIN + timedelta(days=1)


def iter_strings(value: Any, path: str = "$") -> Iterator[Tuple[str, str]]:
    """Every string value and key of a JSON document, in document order."""
    if isinstance(value, dict):
        for key, item in value.items():
            yield f"{path}.<key>", str(key)
            yield from iter_strings(item, f"{path}.{key}")
    elif isinstance(value, list):
        for index, item in enumerate(value):
            yield from iter_strings(item, f"{path}[{index}]")
    elif isinstance(value, str):
        yield path, value


def canonical(value: Any) -> Any:
    """The document with every object's keys sorted, i.e. the on-disk order."""
    if isinstance(value, dict):
        return {key: canonical(value[key]) for key in sorted(value)}
    if isinstance(value, list):
        return [canonical(item) for item in value]
    return value


def _hash_mapping(document: Any, label: str, exempt: frozenset) -> Dict[str, str]:
    """Original hash-like value -> its derivation, numbered by first appearance.

    Numbering follows canonical document order, which is the order the
    committed bytes have and the order ``identity_findings`` reads them in.
    """
    mapping: Dict[str, str] = {}
    counters = {"tx": 0, "sha256": 0, "hex40": 0}
    for _, text in iter_strings(canonical(document)):
        for kind, pattern in (("tx", HEX64_UPPER_RE), ("sha256", HEX64_LOWER_RE), ("hex40", HEX40_RE)):
            for value in pattern.findall(text):
                if value in mapping or value in REVISION_CONSTANTS or value in exempt:
                    continue
                counters[kind] += 1
                if kind == "tx":
                    mapping[value] = synthetic_tx_hash(label, counters[kind])
                elif kind == "sha256":
                    mapping[value] = synthetic_sha256(label, counters[kind])
                else:
                    mapping[value] = synthetic_hex40(label, counters[kind], upper=value.isupper())
    return mapping


def _substitute(value: Any, mapping: Dict[str, str]) -> Any:
    if isinstance(value, dict):
        return {_substitute(key, mapping): _substitute(item, mapping) for key, item in value.items()}
    if isinstance(value, list):
        return [_substitute(item, mapping) for item in value]
    if isinstance(value, str):
        for original, replacement in mapping.items():
            if original in value:
                value = value.replace(original, replacement)
        return value
    return value


def renumber_identities(document: Any, label: str, *, exempt: frozenset = frozenset()) -> Any:
    """A canonical copy of ``document`` whose hash-like values are derivations.

    Identical inputs map to identical outputs, so cross-references inside the
    document (a transaction hash quoted in two places, a code checksum repeated
    in a store event) stay consistent. ``exempt`` lists binding digests that
    are real SHA-256 of fixture bytes and must stay what they are.
    """
    return canonical(_substitute(canonical(document), _hash_mapping(document, label, exempt)))


def identity_findings(
    document: Dict[str, Any],
    label: str,
    *,
    recomputed_digests: Iterable[str] = (),
) -> List[str]:
    """Non-synthetic identities in ``document``; an empty list is the proof.

    The rules mirror the derivations above: every checksum-valid Bech32
    address, of any human-readable part, must be listed in
    ``synthetic_fixture.identities.addresses`` and equal its derivation; every
    32-byte base64 value must be listed in ``identities.pubkeys`` and equal
    its derivation; every 64-hex and 40-hex value must be the k-th derived
    value for its kind in document order, or a listed revision constant, or a
    bound digest; every timestamp must be a whole minute on the synthetic
    clock whatever its zone spelling; and the path and run-folder substrings
    of a real runner must not occur anywhere.

    ``recomputed_digests`` are the SHA-256 values the *caller* recomputed from
    the bytes a bound digest claims to bind (the committed ``raw/go-test.json``,
    the placeholder Wasm module). A digest listed in
    ``synthetic_fixture.bound_digests`` is exempt from the derivation rule only
    when it is among them: the block's own say-so is not enough, otherwise a
    recorded SHA-256 could be laundered by declaring it bound.
    """
    findings: List[str] = []
    block = document.get("synthetic_fixture")
    if not isinstance(block, dict) or block.get("schema") != SCHEMA:
        return [f"{label}: missing synthetic_fixture block with schema {SCHEMA}"]
    if document.get("test_fixture_only") is not True:
        findings.append(f"{label}: test_fixture_only is not true")
    identities = block.get("identities") if isinstance(block.get("identities"), dict) else {}
    addresses = identities.get("addresses") if isinstance(identities.get("addresses"), dict) else {}
    pubkeys = identities.get("pubkeys") if isinstance(identities.get("pubkeys"), dict) else {}
    declared_bound = [str(digest) for digest in (block.get("bound_digests") or ())]
    verified_digests = set(recomputed_digests)
    for digest in declared_bound:
        if digest not in verified_digests:
            findings.append(
                f"{label}: bound digest {digest[:12]}... is declared but was not recomputed from its binding target"
            )
    bound = set(declared_bound) & verified_digests
    expected_addresses = {}
    for role, address in addresses.items():
        derived = synthetic_address(label, role, contract=len(address) == 64)
        if address != derived:
            findings.append(f"{label}: address for role {role!r} is not its derivation")
        expected_addresses[address] = role
    expected_pubkeys = {}
    for key_label, value in pubkeys.items():
        if value != synthetic_pubkey(label, key_label):
            findings.append(f"{label}: public key {key_label!r} is not its derivation")
        expected_pubkeys[value] = key_label
    seen: Dict[str, Dict[str, int]] = {"tx": {}, "sha256": {}, "hex40": {}}
    for path, text in iter_strings({k: v for k, v in document.items() if k != "synthetic_fixture"}):
        for address in find_addresses(text):
            if address not in expected_addresses:
                findings.append(f"{label}: unlisted address {address} at {path}")
        for value in PUBKEY_RE.findall(text):
            if value not in expected_pubkeys:
                findings.append(f"{label}: unlisted 32-byte public key {value[:8]}... at {path}")
        for kind, pattern in (("tx", HEX64_UPPER_RE), ("sha256", HEX64_LOWER_RE)):
            for value in pattern.findall(text):
                if value in bound:
                    continue
                ordinal = seen[kind].setdefault(value, len(seen[kind]) + 1)
                derive = synthetic_tx_hash if kind == "tx" else synthetic_sha256
                if value != derive(label, ordinal):
                    findings.append(f"{label}: {kind} value {value[:12]}... at {path} is not derivation #{ordinal}")
        for value in HEX40_RE.findall(text):
            if value in REVISION_CONSTANTS:
                continue
            ordinal = seen["hex40"].setdefault(value, len(seen["hex40"]) + 1)
            if value != synthetic_hex40(label, ordinal, upper=value.isupper()):
                findings.append(f"{label}: hex40 value {value[:12]}... at {path} is not derivation #{ordinal}")
        for stamp in TIMESTAMP_RE.findall(text):
            if not on_synthetic_clock(stamp):
                findings.append(f"{label}: timestamp {stamp} at {path} is not on the synthetic clock")
        for forbidden in FORBIDDEN_SUBSTRINGS:
            if forbidden in text:
                findings.append(f"{label}: forbidden substring {forbidden!r} at {path}")
    run_id = document.get("run_id")
    if run_id is not None and not str(run_id).startswith("synthetic-"):
        findings.append(f"{label}: run_id {run_id!r} is not synthetic")
    return findings


# ---------------------------------------------------------------------------
# generated boundary fixtures
# ---------------------------------------------------------------------------
GO_DOCUMENT = "go-query-error-classification"
WASM_DOCUMENT = "wasm-query-allowlist-abi"

#: ``harness/go_boundary/go.mod`` module name plus the probe package.
GO_PACKAGE = "github.com/gonka24/forward-e2e-go-boundary/query_faults"
#: ``REQUIRED_TESTS`` in ``scripts/run_go_boundary.py`` and the sub-tests of
#: ``TestToQuerierResultClassifiesVMSystemErrors`` in
#: ``harness/go_boundary/query_faults/plan_test.go``.
GO_REQUIRED_TESTS = ("TestToQuerierResultClassifiesVMSystemErrors", "TestStrictPlanValidation")
GO_SYSTEM_ERROR_SUBTESTS = ("InvalidResponse", "InvalidRequest", "Unknown", "NoSuchContract", "NoSuchCode")
GO_LEVEL = "Go classification and JSON roundtrip, not FFI"
GO_BUILDER = "golang:1.24.2-alpine3.21"

#: ``cases`` of ``scripts/test_wasm_query_boundary.mjs`` (name, envelope,
#: expected SystemError kind or None for the two control cases).
WASM_CASES: Tuple[Tuple[str, str, Optional[str]], ...] = (
    ("malformed-envelope", "{", "invalid_response"),
    ("invalid-envelope-shape", '{"unexpected":true}', "invalid_response"),
    ("invalid_request", '{"error":{"invalid_request":{"error":"bad request","request":"e30="}}}', "invalid_request"),
    ("unknown", '{"error":{"unknown":{}}}', "unknown"),
    ("no_such_contract", '{"error":{"no_such_contract":{"addr":"missing"}}}', "no_such_contract"),
    ("no_such_code", '{"error":{"no_such_code":{"code_id":7}}}', "no_such_code"),
    ("unsupported_request", '{"error":{"unsupported_request":{"kind":"grpc"}}}', "unsupported_request"),
    ("contract-error-control", '{"ok":{"error":"keeper failure"}}', None),
    ("success-control", '{"ok":{"ok":"AQI="}}', None),
)
WASM_LEVEL = "compiled-Wasm query_chain ABI; synthetic host"
#: The serde-json-wasm parse errors cosmwasm_std reports for the two
#: malformed envelopes; the probe records them verbatim under
#: ``error.invalid_response.error``.
_SYSTEM_RESULT_TYPE = (
    "cosmwasm_std::results::system_result::SystemResult"
    "<cosmwasm_std::results::contract_result::ContractResult<cosmwasm_std::binary::Binary>>"
)
WASM_PARSE_ERRORS = {
    "malformed-envelope": f"Error parsing into type {_SYSTEM_RESULT_TYPE}: EOF while parsing a JSON value.",
    "invalid-envelope-shape": (
        f"Error parsing into type {_SYSTEM_RESULT_TYPE}: unknown variant `unexpected`, expected `ok` or `error`"
    ),
}
#: Bytes of the placeholder probe artefact the report is bound to. A valid,
#: empty Wasm module: never executed, only hashed.
WASM_PLACEHOLDER = b"\x00asm\x01\x00\x00\x00"


def json_document_bytes(value: Any) -> bytes:
    """The on-disk encoding of every committed JSON fixture."""
    return (json.dumps(value, indent=2, sort_keys=True) + "\n").encode("utf-8")


#: The wording the four identity-scrubbed live-context documents carry in
#: ``synthetic_fixture.notice``. Defined here, next to the check, so that the
#: documents, the README and ``identity_findings`` cannot drift into claiming
#: different things about the same bytes.
SCRUBBED_NOTICE = (
    "Synthetic offline test fixture derived from a former development receipt. Every chain "
    "identity -- Bech32 address, transaction and block hash, code checksum, node id, validator "
    "public key, timestamp, run id, host path and run label -- was replaced by a labelled SHA-256 "
    "seed derivation with renumber_identities() (see identity_rules); the recorded economic "
    "arithmetic (amounts, heights, epochs, gas, balances, runtime versions, event attributes) was "
    "deliberately kept so the verifier's cross-field rules still meet producer-shaped numbers. "
    "This document is not evidence of any executed chain, Docker or Testermint run and must not be "
    "read as a live receipt: it regresses the arithmetic shape of recorded producer output, never "
    "its identities."
)

#: The wording of the two code-generated boundary fixtures.
GENERATED_NOTICE = (
    "Synthetic offline test fixture generated from code by boundary_fixture_files() in "
    "tests/unit/runner/support/synthetic_evidence.py. No value in it was recorded: placeholder "
    "hashes are labelled SHA-256 seed derivations (see identity_rules) and the one bound digest is "
    "recomputed from the committed bytes it binds. This document is not evidence of any executed "
    "chain, Docker or Wasm probe run."
)

#: The derivation rules every committed document repeats under
#: ``synthetic_fixture.identity_rules``; ``test_synthetic_evidence.py`` pins
#: the documents' copies to this table so the rules cannot be edited in one
#: place only.
IDENTITY_RULES: Dict[str, str] = {
    "seed": f"sha256('{SEED}:' + label)",
    "address": f"bech32('{BECH32_HRP}', seed('<document>:address:<role>')[:20 or 32]), role declared in identities.addresses",
    "pubkey": "base64(seed('<document>:pubkey:<label>')), label declared in identities.pubkeys",
    "tx_hash": "seed('<document>:tx:<n>').hex().upper(), n = order of first appearance",
    "sha256": "seed('<document>:sha256:<n>').hex(), n = order of first appearance",
    "hex40": "seed('<document>:hex40:<n>').hex()[:40], n = order of first appearance",
    "timestamp": f"{CLOCK_ORIGIN.strftime('%Y-%m-%dT%H:%M:%SZ')} + n minutes, preserving relative order",
    "bound_digests": "sha256 of other committed fixture bytes, recomputed by the check; never a recorded digest",
    "checked_by": "tests/unit/runner/test_synthetic_evidence.py",
}

#: The commit on ``main`` whose harness (then ``scripts/a8_acceptance.py``)
#: defines the live-context phase shapes; the relocation to
#: ``scripts/acceptance_harness.py`` changed environment names, scenario
#: aliases and paths, not the phases. It is *not* the shape revision of the
#: generated boundary fixtures, see ``GO_PRODUCER_REVISION``.
HARNESS_SHAPE_REVISION = "8079c0c274f5252800ee16b9f4fb0148bfcae2fe"
#: ``producer_revision`` of the four harness-shaped documents.
HARNESS_PRODUCER_REVISION = (
    f"{HARNESS_SHAPE_REVISION} (then scripts/a8_acceptance.py; the relocation to "
    "scripts/acceptance_harness.py changed environment names, scenario aliases and paths, no phase shape)"
)

#: ``scripts/run_go_boundary.py`` on this branch writes a different report
#: from its predecessor ``scripts/run_a8_go_boundary.py`` at
#: ``HARNESS_SHAPE_REVISION`` (module ``a8-go-boundary``, harness directory
#: ``/app/a8-go-boundary``, package ``./a8faults``). The Go fixture reproduces
#: the post-relocation shape only, so it must not be attributed to that commit.
GO_PRODUCER_REVISION = (
    "refactor/repository-layout (post-relocation scripts/run_go_boundary.py; "
    f"not the scripts/run_a8_go_boundary.py shape of {HARNESS_SHAPE_REVISION[:7]})"
)
GO_PRODUCER_SHAPE_NOTE = (
    "Generated from the producer shape on refactor/repository-layout: module "
    "github.com/gonka24/forward-e2e-go-boundary, harness directory /app/harness/go_boundary, "
    f"package ./query_faults. At {HARNESS_SHAPE_REVISION[:7]} the producer wrote a8-go-boundary, "
    "/app/a8-go-boundary and ./a8faults; this fixture does not reproduce that older shape."
)
#: ``scripts/test_wasm_query_boundary.mjs`` is byte-identical at
#: ``HARNESS_SHAPE_REVISION`` and on this branch, so the Wasm report shape can
#: honestly be attributed to both.
WASM_PRODUCER_REVISION = (
    f"{HARNESS_SHAPE_REVISION} (scripts/test_wasm_query_boundary.mjs is unchanged on refactor/repository-layout)"
)
WASM_PRODUCER_SHAPE_NOTE = (
    "Report keys level, wasm_sha256, node, status and cases[].{name,status,envelope,observed,"
    "query_chain_calls} as the unchanged probe writes them; wasm_sha256 binds the placeholder "
    "module, not a compiled probe."
)


def synthetic_block(document: str, *, producer: str, functions: Tuple[str, ...], purpose: str,
                    producer_revision: str, producer_shape_note: str,
                    notice: str = GENERATED_NOTICE,
                    addresses: Optional[Dict[str, str]] = None,
                    extra: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """The provenance block every committed fixture carries.

    ``producer_revision`` and ``producer_shape_note`` are passed explicitly
    because the two generated fixtures do not share one shape revision (see
    ``GO_PRODUCER_REVISION`` and ``WASM_PRODUCER_REVISION``); a single
    default here is how the Go fixture came to be mis-attributed before.
    """
    block: Dict[str, Any] = {
        "schema": SCHEMA,
        "document": document,
        "notice": notice,
        "purpose": purpose,
        "producer": producer,
        "producer_functions": list(functions),
        "producer_revision": producer_revision,
        "producer_shape_note": producer_shape_note,
        "identity_rules": dict(IDENTITY_RULES),
        "identities": {"addresses": dict(addresses or {})},
    }
    if extra:
        block.update(extra)
    return block


def wasm_abi_report(wasm_bytes: bytes = WASM_PLACEHOLDER, *, node: str = "v24.0.0") -> Dict[str, Any]:
    """The report ``scripts/test_wasm_query_boundary.mjs`` writes for a passing probe.

    ``observed`` is what the compiled ``ExternalQuerier`` decodes from each
    injected envelope: the parsed envelope itself for well-formed ones, and an
    ``invalid_response`` carrying the parser error plus the base64 of the raw
    envelope for the two malformed ones -- the exact assertions of the probe.
    """
    cases = []
    for name, envelope, expected_kind in WASM_CASES:
        if expected_kind == "invalid_response":
            observed: Any = {"error": {"invalid_response": {
                "error": WASM_PARSE_ERRORS[name],
                "response": base64.b64encode(envelope.encode("utf-8")).decode("ascii"),
            }}}
        else:
            observed = json.loads(envelope)
        cases.append({"name": name, "status": "PASS", "envelope": envelope,
                      "observed": observed, "query_chain_calls": 1})
    wasm_sha256 = hashlib.sha256(wasm_bytes).hexdigest()
    return canonical({
        "level": WASM_LEVEL,
        "wasm_sha256": wasm_sha256,
        "node": node,
        "status": "PASS",
        "cases": cases,
        "test_fixture_only": True,
        "synthetic_fixture": synthetic_block(
            WASM_DOCUMENT,
            producer="scripts/test_wasm_query_boundary.mjs",
            functions=("cases", "evidence"),
            purpose="9-case compiled-Wasm query_chain envelope decoding report bound to a placeholder Wasm artefact",
            producer_revision=WASM_PRODUCER_REVISION,
            producer_shape_note=WASM_PRODUCER_SHAPE_NOTE,
            extra={
                "bound_digests": [wasm_sha256],
                "bindings": {"wasm_sha256": "sha256 of the empty Wasm module 0061736d01000000 (never executed)"},
            },
        ),
    })


def go_test_events() -> List[Dict[str, Any]]:
    """``go test -json`` events for the two required tests, in Go's field order."""
    clock = [CLOCK_ORIGIN]

    def stamp() -> str:
        clock[0] = clock[0] + timedelta(milliseconds=1)
        return clock[0].strftime("%Y-%m-%dT%H:%M:%S.") + f"{clock[0].microsecond // 1000:03d}000000Z"

    def event(action: str, test: Optional[str] = None, **fields: Any) -> Dict[str, Any]:
        record: Dict[str, Any] = {"Time": stamp(), "Action": action, "Package": GO_PACKAGE}
        if test is not None:
            record["Test"] = test
        record.update(fields)
        return record

    def run_and_pass(test: str, children: Tuple[str, ...] = ()) -> List[Dict[str, Any]]:
        records = [event("run", test), event("output", test, Output=f"=== RUN   {test}\n")]
        for child in children:
            records.extend(run_and_pass(f"{test}/{child}"))
        records.append(event("output", test, Output=f"--- PASS: {test} (0.00s)\n"))
        records.append(event("pass", test, Elapsed=0))
        return records

    events = [event("start")]
    events.extend(run_and_pass(GO_REQUIRED_TESTS[0], GO_SYSTEM_ERROR_SUBTESTS))
    events.extend(run_and_pass(GO_REQUIRED_TESTS[1]))
    events.append(event("output", Output="PASS\n"))
    events.append(event("output", Output=f"ok  \t{GO_PACKAGE}\t0.010s\n"))
    events.append(event("pass", Elapsed=0.011))
    return events


def go_test_json_bytes() -> bytes:
    return "".join(json.dumps(record, separators=(",", ":")) + "\n" for record in go_test_events()).encode("utf-8")


def go_build_log() -> str:
    """A BuildKit-shaped build transcript with no registry digests."""
    run_filter = "|".join(GO_REQUIRED_TESTS)
    lines = [
        '#0 building with "default" instance using docker driver',
        "",
        "#1 [internal] load build definition from Dockerfile",
        "#1 transferring dockerfile: 2.57kB done",
        "#1 DONE 0.0s",
        "",
        f"#2 [internal] load metadata for docker.io/library/{GO_BUILDER}",
        "#2 DONE 0.0s",
        "",
        "#3 [internal] load build context",
        "#3 transferring context: 1.00MB 0.1s done",
        "#3 DONE 0.1s",
        "",
        "#4 [context harness] load from client",
        "#4 transferring harness: 12.00kB done",
        "#4 DONE 0.0s",
        "",
        f"#5 [builder 1/3] FROM docker.io/library/{GO_BUILDER}",
        "#5 CACHED",
        "",
        "#6 [go-boundary 1/3] COPY --from=harness . /app/go-boundary/",
        "#6 DONE 0.0s",
        "",
        "#7 [go-boundary 2/3] WORKDIR /app/go-boundary",
        "#7 DONE 0.0s",
        "",
        "#8 [go-boundary 3/3] RUN --mount=type=cache,id=go-build-cache,target=/root/.cache/go-build "
        "--mount=type=cache,id=go-mod-cache,target=/go/pkg/mod mkdir -p /boundary-evidence; "
        "go test -mod=mod -tags=muslc -count=1 -json ./query_faults "
        f"-run '{run_filter}' > /boundary-evidence/go-test.json 2>&1; "
        "echo $? > /boundary-evidence/exit-code",
        "#8 DONE 1.0s",
        "",
        "#9 [boundary-evidence 1/1] COPY --from=go-boundary /boundary-evidence/ /",
        "#9 DONE 0.0s",
        "",
        "#10 exporting to client directory",
        "#10 copying files 8.00kB done",
        "#10 DONE 0.0s",
    ]
    return "\n".join(lines) + "\n"


def go_boundary_report(test_json: bytes) -> Dict[str, Any]:
    """``report.json`` in the shape ``scripts/run_go_boundary.py`` writes for a PASS.

    The placeholder hashes below are only distinct tokens; ``renumber_identities``
    turns them into the derivations in document order, keeping every repeated
    token (the Gonka head quoted twice, the go.mod digest quoted four times)
    consistent. ``test_output_sha256`` is the one real digest: it binds the
    committed ``raw/go-test.json`` bytes, as the producer's does.
    """
    document = GO_DOCUMENT
    test_output_sha256 = hashlib.sha256(test_json).hexdigest()
    # Tokens carry a lowercase letter so they classify as lowercase digests:
    # an all-digit string would match the upper-case transaction-hash pattern too.
    token40 = [f"a{index:039x}" for index in range(1, 3)]
    token64 = [f"a{index:063x}" for index in range(1, 7)]
    go_files = {"inference-chain/go.mod": token64[0], "inference-chain/go.sum": token64[1]}
    report = {
        "gonka_sha": token40[0],
        "gonka_tree_sha": token40[1],
        "level": GO_LEVEL,
        "docker_exit": 0,
        "go_exit": "0",
        "dockerfile_sha256": token64[2],
        "harness_module": {
            "dir": "/app/harness/go_boundary",
            "files_sha256": {
                "go.mod": token64[3],
                "query_faults/plan.go": token64[4],
                "query_faults/plan_test.go": token64[5],
            },
        },
        "go_mod_edit_flags": [
            "-module=github.com/gonka24/forward-e2e-go-boundary",
            "-require=github.com/productscience/inference@v0.0.0-00010101000000-000000000000",
            "-replace=github.com/productscience/inference=../inference-chain",
        ],
        "gonka_go_files": {
            "host_before": dict(go_files),
            "host_after": dict(go_files),
            "container_before": dict(go_files),
            "container_after": dict(go_files),
            "unchanged": True,
        },
        "dependency_versions": {
            "gonka_modules": 3,
            "harness_modules": 3,
            "differences": [],
            "match": True,
        },
        "source_snapshot": {
            "before_head": token40[0],
            "before_tree": token40[1],
            "after_problems": [],
            "verdict": "UNCHANGED",
        },
        "status": "PASS",
        "test_output_sha256": test_output_sha256,
        "test_fixture_only": True,
        "synthetic_fixture": synthetic_block(
            document,
            producer="scripts/run_go_boundary.py",
            functions=("generate_dockerfile", "main"),
            purpose="Go query-error classification boundary report whose test_output_sha256 binds raw/go-test.json",
            producer_revision=GO_PRODUCER_REVISION,
            producer_shape_note=GO_PRODUCER_SHAPE_NOTE,
            extra={
                "bound_digests": [test_output_sha256],
                "bindings": {"test_output_sha256": "sha256 of the committed raw/go-test.json bytes"},
            },
        ),
    }
    return renumber_identities(report, document, exempt=frozenset({test_output_sha256}))


def boundary_fixture_files() -> Dict[str, bytes]:
    """Relative path -> bytes of every generated boundary fixture."""
    test_json = go_test_json_bytes()
    return {
        f"{WASM_DOCUMENT}.json": json_document_bytes(wasm_abi_report()),
        f"{GO_DOCUMENT}/report.json": json_document_bytes(go_boundary_report(test_json)),
        f"{GO_DOCUMENT}/raw/go-test.json": test_json,
        f"{GO_DOCUMENT}/raw/exit-code": b"0\n",
        f"{GO_DOCUMENT}/build.log": go_build_log().encode("utf-8"),
    }


if __name__ == "__main__":  # pragma: no cover - regeneration entry point
    import sys
    from pathlib import Path

    target = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parents[4] / "tests" / "fixtures" / "evidence"
    for relative, content in boundary_fixture_files().items():
        path = target / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
        print(f"wrote {path}")
